### ISSUE TITLE
fd1, fd2, rc for `make`

### ISSUE THREAD

**Issue by Zeebrow** [Zeebrow/quickhost#27]
Host starts ok but fails the exit
```
starting hosts...
*****************
2022-07-12 10:27:36,980 : quickhost.temp_data_collector : store_test_data : DEBUG: 0.009253 of 0.026984 sec to write test data to mock-data/AWSHost/create (now 11.24 Kib)
===================Waiting on hosts for 'qwer'=========================
(1/1) Ready: ['i-0b99c8aa052c48c4e'] Waiting: (1): ['i-0b99c8aa052c48c4e']
Done
Traceback (most recent call last):
  File "/home/zeebrow/repos/github.com/zeebrow/quickhost-plugins/plugins/aws/venv/bin/main.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/zeebrow/repos/github.com/zeebrow/quickhost/src/scripts/main.py", line 136, in <module>
    rc, fd1, fd2= main()
TypeError: cannot unpack non-iterable int object
```

**Comment by Zeebrow** [comment]
See #29
